//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOPExercise.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScenarioTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScenarioTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOPExercise.Properties.ScenarioTexts", typeof(ScenarioTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter your choice (1 or 2) to continue: .
        /// </summary>
        internal static string EnterChoiceMessage {
            get {
                return ResourceManager.GetString("EnterChoiceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, enter a fee as much as you want (but not more than you have): .
        /// </summary>
        internal static string EnterFeeMessage {
            get {
                return ResourceManager.GetString("EnterFeeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, dear player! Please, enter your correct name to start the game trip: .
        /// </summary>
        internal static string EnterPlayerNameMessage {
            get {
                return ResourceManager.GetString("EnterPlayerNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not lots of rules. All that you must know: You have 100 AM$ at the beginning of the game..
        /// </summary>
        internal static string InstructionsPoint1 {
            get {
                return ResourceManager.GetString("InstructionsPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this city you will be go along streets and have meetings with different members of local guilds..
        /// </summary>
        internal static string InstructionsPoint2 {
            get {
                return ResourceManager.GetString("InstructionsPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read guidance closely as the game progresses. And my advice for you : Try to survive as long as possible..
        /// </summary>
        internal static string InstructionsPoint3 {
            get {
                return ResourceManager.GetString("InstructionsPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTRUCTIONS.
        /// </summary>
        internal static string InstructionsTitle {
            get {
                return ResourceManager.GetString("InstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You go along the streets of Ankh-Morpork and ... .
        /// </summary>
        internal static string WalkingMessage {
            get {
                return ResourceManager.GetString("WalkingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankh-Morpork lies on the River Ankh (the most polluted waterway on the Discworld and reputedly solid enough to walk on),.
        /// </summary>
        internal static string WelcomeMessagePart1 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where the fertile loam of the Sto Plains meets the Circle Sea. This, naturally, puts it in an excellent trading position..
        /// </summary>
        internal static string WelcomeMessagePart2 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The central city divides more or less into Ankh (the posh part) and Morpork (the humble part,.
        /// </summary>
        internal static string WelcomeMessagePart3 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to which includes the slum area known as \&quot;the Shades\&quot;), which are separated by the River Ankh..
        /// </summary>
        internal static string WelcomeMessagePart4 {
            get {
                return ResourceManager.GetString("WelcomeMessagePart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the fine city of Ankh-Morpork!.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It can be dangerous to walk the streets. So watch out!.
        /// </summary>
        internal static string WelcomeWarningMessage {
            get {
                return ResourceManager.GetString("WelcomeWarningMessage", resourceCulture);
            }
        }
    }
}
